'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     GitVersion
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

<Global.System.Runtime.CompilerServices.CompilerGenerated()>
NotInheritable Class GitVersionInformation
    Private Sub New()
    End Sub
{0}
End Class
