pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
  - name: Automatic merge on dependabot PR after success CI
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=DotNet Format
      - check-success=Build (windows-latest)
      - check-success=Build (ubuntu-latest)
      - check-success=Build (macos-latest)
      - check-success=Unit Test (windows-latest)
      - check-success=Unit Test (ubuntu-latest)
      - check-success=Unit Test (macos-latest)
      - check-success=Release
    actions:
      merge:
        method: rebase
        strict: smart
  - name: Thank contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
