image: Visual Studio 2017

environment:
  DOCKER_USERNAME:
    secure: EbFuNVc5k/p9AiaBmS839D4GqsNaMlJ3djyRR5b2fjM=
  DOCKER_PASSWORD:
    secure: kweTIFTVyAVyKlvcIvgffpNa6qK8wyWAekVgue8WFqI=

install:
  - npm i -g tfx-cli
  - docker version

assembly_info:
  patch: false

build_script:
  - ps: .\deploy.ps1

test: off
skip_non_tags: true
