''------------------------------------------------------------------------------
'' <auto-generated>
'' This code was generated by GitVersion.
''
'' You can modify this code as we will not overwrite it when re-executing GitVersion
'' </auto-generated>
''------------------------------------------------------------------------------

Imports System.Reflection

<Assembly: AssemblyFileVersion("0.0.0.0")>
<Assembly: AssemblyVersion("0.0.0.0")>
<Assembly: AssemblyInformationalVersion("0.0.0.0")>
