//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GitVersion
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if NET20 || NET35 || NETCOREAPP1_0 || NETCOREAPP1_1 || NETSTANDARD1_0 || NETSTANDARD1_1 || NETSTANDARD1_2 || NETSTANDARD1_3 || NETSTANDARD1_4 || NETSTANDARD1_5 || NETSTANDARD1_6
namespace System.Diagnostics.CodeAnalysis

[<Sealed>]
[<global.System.AttributeUsage(
    global.System.AttributeTargets.Assembly ||| 
    global.System.AttributeTargets.Class ||| 
    global.System.AttributeTargets.Struct ||| 
    global.System.AttributeTargets.Constructor ||| 
    global.System.AttributeTargets.Method ||| 
    global.System.AttributeTargets.Property ||| 
    global.System.AttributeTargets.Event, 
    Inherited = false, AllowMultiple = false)>]
type ExcludeFromCodeCoverageAttribute() = inherit global.System.Attribute()
#endif

namespace global

[<AbstractClass; Sealed>]
[<global.System.Runtime.CompilerServices.CompilerGenerated>]
[<global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
type GitVersionInformation =
{0}
