name: 'Artifacts restore'
description: 'Artifacts restore'

runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      name: Download native linux packages
      with:
        name: native-Linux
        path: ${{ github.workspace }}/artifacts/packages/native

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      name: Download native windows packages
      with:
        name: native-Windows
        path: ${{ github.workspace }}/artifacts/packages/native

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      name: Download native macos packages
      with:
        name: native-macOS
        path: ${{ github.workspace }}/artifacts/packages/native

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      name: Download nuget packages
      with:
        name: nuget
        path: ${{ github.workspace }}/artifacts/packages/nuget
