name: 'Docker Setup'
description: 'Setups the docker engine'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker
      uses: docker/setup-docker-action@0234bb73ccb40f0c430b795634f9247e2b5c2d23 # v5
      with:
        daemon-config: '{ "features": { "containerd-snapshotter": true } }'
