name: 'Docker Setup'
description: 'Setups the docker engine'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker
      uses: docker/setup-docker-action@b2189fbf2a6592b51fee7cdd93ee2bfaeba733db # v5.1.0
      with:
        daemon-config: '{ "features": { "containerd-snapshotter": true } }'
