name: 'Docker Setup'
description: 'Setups the docker engine'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker
      uses: docker/setup-docker-action@77e84dbf09b47d1e29270283c22f16145aa85ca1 # v5.4.0
      with:
        daemon-config: '{ "features": { "containerd-snapshotter": true } }'
