name: 'Docker Test'
description: 'Docker Test Images'
inputs:
  arch:
    description: 'Docker architecture'
    default: 'amd64'
  docker_distro:
    description: 'Linux Distro'
    default: 'debian.12'
  dotnet_version:
    description: '.net version'
    default: '8.0'

runs:
  using: 'composite'
  steps:
  -
    name: '[Docker Build & Test] DockerHub'
    shell: pwsh
    run: |
        dotnet run/docker.dll --target=DockerTest `
              --arch=${{ inputs.arch }} --dotnet_version=${{ inputs.dotnet_version }} `
              --docker_distro=${{ inputs.docker_distro }} --docker_registry dockerhub --verbosity=diagnostic
  -
    name: '[Docker Build & Test] GitHub'
    shell: pwsh
    run: |
        dotnet run/docker.dll --target=DockerTest `
              --arch=${{ inputs.arch }} --dotnet_version=${{ inputs.dotnet_version }} `
              --docker_distro=${{ inputs.docker_distro }} --docker_registry github --verbosity=diagnostic
