name: 🐞 Bug/Issue report
description: Create a report to help us improve
title: "[ISSUE]: <title>"
labels: ["needs triage"]
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: I have written a descriptive issue title
      required: true
    - label: I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported
      required: true
- type: dropdown
  attributes:
    label: GitVersion package
    options:
    - GitVersion.Tool
    - GitVersion.MsBuild
    - GitVersion.Portable
    - gittools/actions
    - AzureDevops task
    multiple: true
  validations:
    required: true
- type: input
  attributes:
    label: GitVersion version
  validations:
    required: true
- type: dropdown
  attributes:
    label: Operating system
    options:
    - Linux
    - Windows
    - macOS
    - N/A
    multiple: true
  validations:
    required: true
- type: textarea
  attributes:
    label: What are you seeing?
    description: Describe the issue you are seeing
  validations:
    required: true
- type: textarea
  attributes:
    label: What is expected?
    description: Describe what you would expect
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: List of steps or sample project to reproduce the issue
  validations:
    required: true
- type: textarea
  attributes:
    label: RepositoryFixture Test
    description: If you are able to write your bug or scenario up as a `RepositoryFixture` test and submit a pull-request with it, it is going to increase the likelyhood of the bug being fixed. Make sure there is no sensitive data shared and that you place a stack trace inside a code (```csharp) block to avoid formatting issues.
  validations:
    required: false    
- type: textarea
  attributes:
    label: Output log or link to your CI build (if appropriate).
    description: Log messages you receive when running. Make sure there is no sensitive data shared. No need for backticks here.
    render: shell
  validations:
    required: false