// The artifact checks supply GitVersionMsBuildVersion and TargetFramework at build time.
#:property OutputType=Exe
#:property RootNamespace=App
#:property AssemblyName=app
#:property OutputPath=./build/
#:property GenerateAssemblyInfo=false
#:property PublishAot=false
#:property ManagePackageVersionsCentrally=false
#:property RestoreAdditionalProjectSources=https://api.nuget.org/v3/index.json
#:package GitVersion.MsBuild@$(GitVersionMsBuildVersion)

using System;

namespace App
{
    static class Program
    {
        /// <summary>
        /// Prints the version generated by the MSBuild package for the artifact runner to validate.
        /// </summary>
        static void Main(string[] args)
        {
            Console.Write(GitVersionInformation.FullSemVer);
        }
    }
}
