name: 'Docker Manifests'
description: 'Docker Publish Manifests'
inputs:
  docker_distro:
    description: 'Linux Distro'
    required: true
  dotnet_version:
    description: '.net version'
    required: true
  docker_registry_username:
    description: 'DockerHub Registry Username'
    required: true
  docker_registry_password:
    description: 'DockerHub Registry Password'
    required: true
  github_registry_username:
    description: 'GitHub Registry Username'
    required: true
  github_registry_password:
    description: 'GitHub Registry Password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
      with:
        username: ${{ inputs.docker_registry_username }}
        password: ${{ inputs.docker_registry_password }}

    - name: '[Docker Publish Manifests] DockerHub'
      shell: pwsh
      env:
        DOTNET_VERSION: ${{ inputs.dotnet_version }}
        DOCKER_DISTRO: ${{ inputs.docker_distro }}
      run: |
        dotnet run/docker.dll `
              --target=DockerManifest --arch=amd64 --arch=arm64 --dotnet_version=$env:DOTNET_VERSION `
              --docker_distro=$env:DOCKER_DISTRO --docker_registry dockerhub

    - name: Login to GitHub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
      with:
        registry: ghcr.io
        username: ${{ inputs.github_registry_username }}
        password: ${{ inputs.github_registry_password }}

    - name: '[Docker Publish Manifests] GitHub'
      shell: pwsh
      env:
        DOTNET_VERSION: ${{ inputs.dotnet_version }}
        DOCKER_DISTRO: ${{ inputs.docker_distro }}
      run: |
        dotnet run/docker.dll `
              --target=DockerManifest --arch=amd64 --arch=arm64 --dotnet_version=$env:DOTNET_VERSION `
              --docker_distro=$env:DOCKER_DISTRO --docker_registry github
