name: 'Cache restore'
description: 'Cache restore'

runs:
  using: 'composite'
  steps:
    - name: Use cached cake frosting
      id: cache-cake
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: run
        key: run-${{ runner.os }}-${{ hashFiles('./build/**') }}

    - name: Use cached tools
      id: cache-tools
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: tools
        key: tools-${{ runner.os }}-${{ hashFiles('./build/**') }}

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        global-json-file: global.json
