name: 'Cache restore'
description: 'Cache restore'

runs:
  using: 'composite'
  steps:
    - name: Use cached cake frosting
      id: cache-cake
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: run
        key: run-${{ runner.os }}-${{ hashFiles('./build/**') }}

    - name: Use cached tools
      id: cache-tools
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: tools
        key: tools-${{ runner.os }}-${{ hashFiles('./build/**') }}

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        global-json-file: global.json
