//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("0.0.0.0")]