<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="LibGit2Sharp" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" VersionOverride="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GitVersion.Core\GitVersion.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="GitVersion.Core.Tests" />
        <InternalsVisibleTo Include="GitVersion.MsBuild.Tests" />
        <InternalsVisibleTo Include="GitVersion.Output.Tests" />
    </ItemGroup>

</Project>
