//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GitVersion
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

//------------------------------------------------------------------------------
//What the values SHOULD look like after the template is applied:
//#define VERSION_FULL	MAJORVERSION,MINORVERSION,BUILDVERSION,REVISIONVERSION
//#define VERSION_STRING VERSION_XSTR(MAJORVERSION.MINORVERSION.BUILDVERSION.REVISIONVERSION-REVISIONHASH) VERSION_BLANK "\0"

//NOTE:  The trailing "\0" is VERY important

//------------------------------------------------------------------------------

#define VERSION_STR(x)			#x
#define VERSION_XSTR(x)			VERSION_STR(x)
#define VERSION_BLANK ""

#define VERSION_FULL	0,0,0,1
#define VERSION_STRING VERSION_XSTR(0.0.0.1) VERSION_BLANK "\0"   
