sequenceDiagram
    participant main
    activate main
    main->>main: tag 1.2.0
    rect rgb(211, 211, 211)
        Note over main: 1.2.0
    end
    create participant support as support/1.x
    main->>support: branch from tag (1.2.0)
    activate support
    rect rgb(211, 211, 211)
        Note over support: 1.2.0
    end
    support->>support: commit
    rect rgb(211, 211, 211)
        Note over support: 1.2.1-1
    end
    main->>main: Commit '+semver: major'
    rect rgb(211, 211, 211)
        Note over main: 2.0.0-1
    end
    main->>main: tag 2.0.0
    rect rgb(211, 211, 211)
        Note over main: 2.0.0
    end
    create participant hotfix as hotfix/1.2.2
    support->>hotfix: branch from support/1.x
    deactivate support
    activate hotfix
    rect rgb(211, 211, 211)
        Note over hotfix: 1.2.2-beta.1+1
    end
    hotfix->>hotfix: commit
    hotfix->>hotfix: commit
    rect rgb(211, 211, 211)
        Note over hotfix: 1.2.2-beta.1+3
    end
    hotfix->>hotfix: tag 1.2.3-beta.1
    rect rgb(211, 211, 211)
        Note over hotfix: 1.2.3-beta.2+0
    end
    hotfix->>hotfix: commit
    rect rgb(211, 211, 211)
        Note over hotfix: 1.2.3-beta.2+1
    end
    hotfix->>support: merge
    Note over hotfix: Hotfix branches should<br/>be deleted once merged
    destroy hotfix
    support--xhotfix: delete branch
    rect rgb(211, 211, 211)
        Note over support: 1.2.3-5
    end
    activate support
    support->>support: tag 1.2.3
    rect rgb(211, 211, 211)
        Note over support: 1.2.3
    end
    rect rgb(211, 211, 211)
        Note over main: 2.0.0
    end
    support->>main: merge
    rect rgb(211, 211, 211)
        Note over main: 2.0.1-6
    end
    main->>main: tag 2.0.1
    rect rgb(211, 211, 211)
        Note over main: 2.0.1
    end
    support->>support: commit
    rect rgb(211, 211, 211)
        Note over support: 1.2.4-1
    end
    support->>support: tag 1.2.4
    rect rgb(211, 211, 211)
        Note over support: 1.2.4
    end
    support->>main: merge
    rect rgb(211, 211, 211)
        Note over main: 2.0.2-2
    end
    main->>main: tag 2.0.2
    rect rgb(211, 211, 211)
        Note over main: 2.0.2
    end
