sequenceDiagram
    activate main
    main->>main: tag 1.2.0
    rect rgb(211, 211, 211)
        Note over main: 1.2.0
    end
    create participant release as release/next
    main->>release: branch from main
    activate release
    deactivate main
    rect rgb(211, 211, 211)
        Note over release: 1.3.0-beta.1+0
    end
    release->>release: commit
    rect rgb(211, 211, 211)
        Note over release: 1.3.0-beta.1+1
    end
    activate main
    main->>main: commit
    rect rgb(211, 211, 211)
        Note over main: 1.2.1-1
    end
    main->>main: tag 1.2.1
    rect rgb(211, 211, 211)
        Note over main: 1.2.1
    end
    main->>release: merge
    deactivate main
    rect rgb(211, 211, 211)
        Note over release: 1.3.0-beta.1+2
    end
    release->>release: Commit '+semver: major'
    rect rgb(211, 211, 211)
        Note over release: 2.0.0-beta.1+3
    end
    release->>release: tag 2.0.1-beta.1
    rect rgb(211, 211, 211)
        Note over release: 2.0.1-beta.2+0
    end
    release->>release: commit
    rect rgb(211, 211, 211)
        Note over release: 2.0.1-beta.2+1
    end
    create participant pull as pull/2/merge
    main->>pull: branch from main
    activate pull
    release->>pull: merge
    rect rgb(211, 211, 211)
        Note over pull: 2.0.1-PullRequest2.5
    end
    destroy pull
    main--xpull: delete branch
    release->>main: merge
    Note over release: Release branches should<br/>be deleted once merged
    destroy release
    main--xrelease: delete branch
    rect rgb(211, 211, 211)
        Note over main: 2.0.1-5
    end
    activate main
    main->>main: commit
    rect rgb(211, 211, 211)
        Note over main: 2.0.1-6
    end
    main->>main: tag 2.0.1
    rect rgb(211, 211, 211)
        Note over main: 2.0.1
    end
