sequenceDiagram
    participant Config
    participant Next as NextVersionCalculator
    participant Base as BaseVersionCalculator
    participant Metadata as BuildMetadataCreator

    Next->>Base: GetBaseVersion
    Note right of Base: Determine the base version
    Base-->>Next: 2.0.0 at 25e4ba

    alt Base version allows increment
        Config->>Next: Branch increment strategy (patch)
        Next->>Next: Increment using the configured strategy
        Note right of Next: 2.0.1
    end

    alt Base version has a pre-release tag
        Next->>Next: Increment the pre-release number
        Note right of Next: 2.0.1-alpha.2
    else Apply the current branch pre-release tag
        Config->>Next: Pre-release tag for current branch (alpha)
        Next->>Next: Apply configuration to pre-release
        Note right of Next: 2.0.1-alpha.1
    end

    Next->>Metadata: Context
    Metadata-->>Next: Commit count and branch/SHA metadata
    Next->>Next: Apply commit count and metadata
    Note right of Next: 2.0.1-alpha.1+10
