FROM mcr.microsoft.com/devcontainers/dotnet:dev-8.0@sha256:34f4c4a5f6921ff4c147ee3224d4e4af92d479799bd65d9cfbbcb499c0594e90

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
