FROM mcr.microsoft.com/dotnet/sdk@sha256:335dfd6679df1025209964f3e2592c0f1808501d17b9295640fd1a41d132c117

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
