name: 'Artifacts attestation'
description: 'Artifacts attestation'

runs:
  using: 'composite'
  steps:
    - name: 'Attestation'
      uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
      with:
        subject-path: |
          ${{ github.workspace }}/artifacts/packages/native
          ${{ github.workspace }}/artifacts/packages/nuget
