name: 'Artifacts attestation'
description: 'Artifacts attestation'

runs:
  using: 'composite'
  steps:
    - name: 'Attestation'
      uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
      with:
        subject-path: |
          ${{ github.workspace }}/artifacts/packages/native
          ${{ github.workspace }}/artifacts/packages/nuget
