parameters:
- name: name  # defaults for any parameters that aren't specified
  default: ''
- name: vmImage
  default: ''

jobs:
- job: Artifacts_Test_${{ parameters.name }}
  displayName: 'Artifacts Test ${{ parameters.name }}'
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: Generator
  strategy:
    matrix: $[ dependencies['Generator'].outputs['Map_${{ parameters.name }}.dockerConfigs'] ]
  steps:
  - template: common-steps.yml
    parameters:
      includeArtifacts: true
  - pwsh: ./build.ps1 -target Artifacts-Test -DockerDistro $(DISTRO) -DockerDotnetVersion $(DOTNET_VERSION)
    displayName: '[Docker Test Artifacts]'
- job: Artifacts_Test_MsBuild
  displayName: Artifacts Test MsBuild (Windows)
  pool:
    vmImage: windows-latest
  steps:
  - template: common-steps.yml
    parameters:
      includeArtifacts: true
  - pwsh: ./build.ps1 -target Artifacts-MsBuildFull-Test
    displayName: '[MsBuild Test Artifacts]'
