steps:
- template: common-steps.yml
- pwsh: ./build.ps1 -target Pack
  displayName: '[Cake build & pack]'
- publish: $(System.DefaultWorkingDirectory)
  displayName: 'Upload pipeline artifacts'
  condition: and(succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ))
  artifact: storage
