parameters:
- name: name  # defaults for any parameters that aren't specified
  default: ''
- name: vmImage
  default: ''

jobs:
- job: Docker_${{ parameters.name }}
  displayName: 'Docker ${{ parameters.name }}'
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: Generator
  strategy:
    matrix: $[ dependencies['Generator'].outputs['Map_${{ parameters.name }}.dockerConfigs'] ]
  steps:
  - template: common-steps.yml
    parameters:
      includeArtifacts: true
  - pwsh: ./build.ps1 -target Publish-DockerHub -DockerDistro $(DISTRO) -DockerDotnetVersion $(DOTNET_VERSION)
    displayName: '[Docker build]'
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      ENABLED_PUBLISH_DOCKER: $(ENABLED_PUBLISH_DOCKER)
