on:
  workflow_call:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"

jobs:
  artifacts:
    name: ${{ matrix.package }}
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        package: [ Executable, MsBuildFull ]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Restore State
        uses: ./.github/actions/cache-restore

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        name: Download nuget packages
        with:
          name: nuget
          path: ${{ github.workspace }}/artifacts/packages/nuget

      - name: '[Test Artifacts]'
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
        with:
          shell: pwsh
          timeout_minutes: 30
          max_attempts: 3
          retry_on: error
          command: dotnet run/artifacts.dll --target=Artifacts${{ matrix.package }}Test
