on:
  workflow_call:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2025-vs2026, ubuntu-24.04, macos-26 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Restore State
        uses: ./.github/actions/cache-restore

      - name: '[Build]'
        shell: pwsh
        run: dotnet run/build.dll --target=Package

      - name: 'Upload nuget packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.os == 'windows-2025-vs2026'
        with:
          name: nuget
          path: ${{ github.workspace }}/artifacts/packages/nuget

      - name: 'Upload native packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.os == 'windows-2025-vs2026'
        with:
          name: native-${{ runner.os }}
          path: ${{ github.workspace }}/artifacts/packages/native/*.zip

      - name: 'Upload native packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.os != 'windows-2025-vs2026'
        with:
          name: native-${{ runner.os }}
          path: ${{ github.workspace }}/artifacts/packages/native/*.tar.gz
