on:
  workflow_call:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2025-vs2026, ubuntu-24.04, macos-26 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Restore State
        uses: ./.github/actions/cache-restore

      - name: '[Build]'
        shell: pwsh
        run: dotnet run/build.dll --target=Package

      - name: 'Upload nuget packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.os == 'windows-2025-vs2026'
        with:
          name: nuget
          path: ${{ github.workspace }}/artifacts/packages/nuget

      - name: 'Upload native packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.os == 'windows-2025-vs2026'
        with:
          name: native-${{ runner.os }}
          path: ${{ github.workspace }}/artifacts/packages/native/*.zip

      - name: 'Upload native packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.os != 'windows-2025-vs2026'
        with:
          name: native-${{ runner.os }}
          path: ${{ github.workspace }}/artifacts/packages/native/*.tar.gz
