on:
  workflow_call:
    outputs:
      docker_distros:
        description: 'List of Docker distros'
        value: ${{ jobs.set_matrix.outputs.docker_distros }}
      dotnet_versions:
        description: 'List of .NET versions'
        value: ${{ jobs.set_matrix.outputs.dotnet_versions }}

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"

jobs:
  prepare:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2025-vs2026, ubuntu-24.04, macos-26 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache cake frosting
        id: cache-cake
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: run
          key: run-${{ runner.os }}-${{ hashFiles('./build/**') }}

      - name: Use cached tools
        id: cache-tools
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: tools
          key: tools-${{ runner.os }}-${{ hashFiles('./build/**') }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          global-json-file: global.json

      - name: '[Build]'
        if: steps.cache-cake.outputs.cache-hit != 'true'
        run: dotnet build build/ --configuration=Release

      - name: '[Prepare]'
        shell: pwsh
        run: dotnet run/build.dll --target=BuildPrepare
  set_matrix:
    needs: [ prepare ]
    name: Set Matrix
    runs-on: ubuntu-24.04
    outputs:
      docker_distros: ${{ steps.set_matrix.outputs.docker_distros }}
      dotnet_versions: ${{ steps.set_matrix.outputs.dotnet_versions }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Restore State
        uses: ./.github/actions/cache-restore

      - name: '[Matrix]'
        id: set_matrix
        shell: pwsh
        run: dotnet run/config.dll --target=SetMatrix
