on:
  workflow_call:
    inputs:
      publish_packages:
        required: true
        type: boolean

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"

permissions:
  contents: read

jobs:
  publish:
    name: ${{ matrix.taskName }}
    runs-on: windows-2025-vs2026
    permissions:
      id-token: write
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        taskName: [ NuGet, Chocolatey ]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Restore State
        uses: ./.github/actions/cache-restore

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        name: Download nuget packages
        with:
          name: nuget
          path: ${{ github.workspace }}/artifacts/packages/nuget

      - name: Load NuGet credentials
        id: nuget-creds
        if: inputs.publish_packages
        uses: gittools/cicd/nuget-creds@824c3d773fb5d1b00c26b474ae88b7ce9ae555ee # v5
        with:
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load Chocolatey credentials
        id: choco-creds
        if: inputs.publish_packages
        uses: gittools/cicd/choco-creds@824c3d773fb5d1b00c26b474ae88b7ce9ae555ee # v5
        with:
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: '[Publish]'
        if: inputs.publish_packages
        shell: pwsh
        run: dotnet run/publish.dll --target=Publish${{ matrix.taskName }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NUGET_API_KEY: ${{ steps.nuget-creds.outputs.nuget_api_key }}
          CHOCOLATEY_API_KEY: ${{ steps.choco-creds.outputs.choco_api_key }}
