on:
  workflow_call:
    inputs:
      publish_packages:
        required: true
        type: boolean

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"

jobs:
  publish:
    name: ${{ matrix.taskName }}
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        taskName: [ NuGet, Chocolatey ]

    steps:
    -
      name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    -
      name: Restore State
      uses: ./.github/actions/cache-restore
    -
      uses: actions/download-artifact@v8
      name: Download nuget packages
      with:
        name: nuget
        path: ${{ github.workspace }}/artifacts/packages/nuget

    -
      name: Load NuGet credentials
      id: nuget-creds
      if: inputs.publish_packages
      uses: gittools/cicd/nuget-creds@main
      with:
        op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    -
      name: Load Chocolatey credentials
      id: choco-creds
      if: inputs.publish_packages
      uses: gittools/cicd/choco-creds@main
      with:
        op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    -
      name: '[Publish]'
      if: inputs.publish_packages
      shell: pwsh
      run: dotnet run/publish.dll --target=Publish${{ matrix.taskName }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        NUGET_API_KEY: ${{ steps.nuget-creds.outputs.nuget_api_key }}
        CHOCOLATEY_API_KEY: ${{ steps.choco-creds.outputs.choco_api_key }}
