on:
  workflow_call:
    inputs:
      dotnet_versions:
        required: true
        type: string
      publish_coverage:
        required: true
        type: boolean
env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"

permissions:
  contents: read

jobs:
  unit_test:
    name: ${{ matrix.os }} - net${{ matrix.dotnet_version }}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2025-vs2026, ubuntu-24.04, macos-26 ]
        dotnet_version: ${{ fromJson(inputs.dotnet_versions) }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Restore State
        uses: ./.github/actions/cache-restore

      - name: '[Unit Test]'
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          shell: pwsh
          timeout_minutes: 30
          max_attempts: 3
          retry_on: error
          command: 'dotnet run/build.dll --target=UnitTest --dotnet_version=${{ matrix.dotnet_version }}'

      - name: Test Summary
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2.6
        if: always() && matrix.dotnet_version == '10.0'
        with:
          paths: artifacts/test-results/**/results.xml

      - name: Upload Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: success() && inputs.publish_coverage && matrix.dotnet_version == '10.0'
        with:
          files: artifacts/test-results/**/results.xml
          report_type: 'test_results'
          use_oidc: true

      - name: Upload Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: success() && inputs.publish_coverage && matrix.dotnet_version == '10.0'
        with:
          directory: artifacts/test-results
          report_type: 'coverage'
          use_oidc: true
