name: Actionlint
on:
  push:
    branches:
      - main
      - 'fix/*'
      - 'feature/*'
      - 'poc/*'
      - 'support/*'
      - 'next/*'
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/actionlint.yaml'

  pull_request:
    branches:
      - main
      - 'support/*'
      - 'next/*'
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/actionlint.yaml'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    name: Actionlint
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283 # v1.73.1
        with:
          github_token: ${{ github.token }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          fail_on_error: true
