name: Actionlint

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - 'fix/*'
      - 'feature/*'
      - 'poc/*'
      - 'support/*'
      - 'next/*'
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/actionlint.yaml'

  pull_request:
    branches:
      - main
      - 'support/*'
      - 'next/*'
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/actionlint.yaml'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    name: Actionlint
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@d290e336d5a743810aef4404f757dc862276d2ae # v1.73.4
        with:
          github_token: ${{ github.token }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          fail_on_error: true
