name: Markdown Update
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'

  pull_request:
    branches:
      - main
      - 'support/*'
      - 'next/*'
    paths:
      - 'docs/**'

env:
  DOTNET_ROLL_FORWARD: "Major"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

defaults:
  run:
    shell: pwsh

jobs:
  docs:
    name: Update Markdown (embedded snippets)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: gittools/cicd/checkout@v1
        with:
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          fetch-depth: 1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Run MarkdownSnippets
        run: |
          dotnet tool install --global MarkdownSnippets.Tool
          mdsnippets --write-header false
        working-directory: ${{ github.workspace }}/docs/input

      - name: Commit and push markdown docs changes
        uses: gittools/cicd/git-commit-push@v1
        with:
          message: "include markdown docs changes"
