name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
          os: [linux]
          targetFramework: [2.1, 3.1]
          distro: [centos-7, debian-9, fedora-30, ubuntu-16.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo ${{ matrix.os }}_${{ matrix.targetFramework }}_${{ matrix.distro }}
